CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(30) NOT NULL,
    fecha_registro TIMESTAMP
);

CREATE TABLE IF NOT EXISTS perfil_negocio (
    id_usuario INTEGER PRIMARY KEY,
    ruc VARCHAR(11) NOT NULL UNIQUE,
    razon_social VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS perfil_deportista (
    id_usuario INTEGER PRIMARY KEY,
    nombre_completo VARCHAR(255),
    dni VARCHAR(8) NOT NULL UNIQUE,
    disciplina VARCHAR(255) NOT NULL,
    biografia VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS plantilla_metas (
    id_plantilla INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_meta VARCHAR(255),
    descripcion_sugerida VARCHAR(1000),
    tipo_entregable VARCHAR(50),
    precio_sugerido NUMERIC(14,2)
);

CREATE TABLE IF NOT EXISTS contratos (
    id_contrato INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_negocio INTEGER NOT NULL,
    id_deportista INTEGER NOT NULL,
    monto_total NUMERIC(14,2) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    fecha_creacion TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metas_contrato (
    id_meta_contrato INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato INTEGER NOT NULL,
    id_plantilla INTEGER NOT NULL,
    descripcion_acordada VARCHAR(1000) NOT NULL,
    monto_deportista NUMERIC(14,2) NOT NULL,
    monto_negocio NUMERIC(14,2) NOT NULL,
    comentario_deportista VARCHAR(1000),
    url_evidencia VARCHAR(2048),
    estado VARCHAR(30) NOT NULL,
    fecha_actualizacion TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fondo_garantia (
    id_contrato INTEGER PRIMARY KEY,
    monto_congelado NUMERIC(14,2) NOT NULL,
    ultima_actualizacion TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transacciones (
    id_transaccion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato INTEGER NOT NULL,
    id_meta_contrato INTEGER NOT NULL,
    monto_neto NUMERIC(14,2) NOT NULL,
    comision_plataforma NUMERIC(14,2) NOT NULL,
    fecha_ejecucion TIMESTAMP
);
