ALTER TABLE contratos ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE metas_contrato ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE fondo_garantia ADD COLUMN IF NOT EXISTS monto_inicial NUMERIC(14,2);
ALTER TABLE fondo_garantia ADD COLUMN IF NOT EXISTS monto_liberado NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE fondo_garantia ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

UPDATE fondo_garantia SET monto_inicial = monto_congelado WHERE monto_inicial IS NULL;
ALTER TABLE fondo_garantia ALTER COLUMN monto_inicial SET NOT NULL;

CREATE TABLE IF NOT EXISTS evidencias (
    id_evidencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_meta_contrato INTEGER NOT NULL,
    numero_intento INTEGER NOT NULL,
    nombre_original VARCHAR(255) NOT NULL,
    tipo_mime VARCHAR(100) NOT NULL,
    tamanio_bytes BIGINT NOT NULL,
    hash_sha256 VARCHAR(64) NOT NULL,
    comentario_deportista VARCHAR(1000),
    estado VARCHAR(30) NOT NULL,
    motivo_rechazo VARCHAR(1000),
    fecha_carga TIMESTAMP NOT NULL,
    fecha_revision TIMESTAMP,
    id_usuario_revisor INTEGER,
    fecha_actualizacion TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_evidencia_tamanio_positivo CHECK (tamanio_bytes > 0),
    CONSTRAINT ck_evidencia_intento_positivo CHECK (numero_intento > 0),
    CONSTRAINT ck_evidencia_estado CHECK (estado IN ('EN_REVISION', 'APROBADA', 'RECHAZADA')),
    CONSTRAINT uq_evidencia_meta_intento UNIQUE (id_meta_contrato, numero_intento)
);

CREATE TABLE IF NOT EXISTS archivos_evidencia (
    id_evidencia BIGINT PRIMARY KEY,
    contenido BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS notificaciones (
    id_notificacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    mensaje VARCHAR(500) NOT NULL,
    entidad_relacionada VARCHAR(80) NOT NULL,
    id_entidad VARCHAR(80) NOT NULL,
    fecha TIMESTAMP NOT NULL,
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_lectura TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auditoria_acciones (
    id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER,
    accion VARCHAR(100) NOT NULL,
    entidad VARCHAR(80) NOT NULL,
    id_entidad VARCHAR(80) NOT NULL,
    fecha TIMESTAMP NOT NULL,
    resultado VARCHAR(40) NOT NULL,
    informacion_adicional VARCHAR(1000)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_evidencia_activa_por_meta
    ON evidencias (id_meta_contrato) WHERE estado = 'EN_REVISION';
CREATE UNIQUE INDEX IF NOT EXISTS uq_transaccion_meta
    ON transacciones (id_meta_contrato);
CREATE INDEX IF NOT EXISTS idx_evidencias_meta ON evidencias (id_meta_contrato);
CREATE INDEX IF NOT EXISTS idx_evidencias_estado ON evidencias (estado);
CREATE INDEX IF NOT EXISTS idx_evidencias_fecha ON evidencias (fecha_carga);
CREATE INDEX IF NOT EXISTS idx_metas_contrato ON metas_contrato (id_contrato);
CREATE INDEX IF NOT EXISTS idx_metas_estado ON metas_contrato (estado);
CREATE INDEX IF NOT EXISTS idx_contratos_negocio ON contratos (id_negocio);
CREATE INDEX IF NOT EXISTS idx_contratos_deportista ON contratos (id_deportista);
CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario_leida ON notificaciones (id_usuario, leida);
CREATE INDEX IF NOT EXISTS idx_auditoria_entidad ON auditoria_acciones (entidad, id_entidad);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_perfil_negocio_usuario') THEN
        ALTER TABLE perfil_negocio ADD CONSTRAINT fk_perfil_negocio_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_perfil_deportista_usuario') THEN
        ALTER TABLE perfil_deportista ADD CONSTRAINT fk_perfil_deportista_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_negocio') THEN
        ALTER TABLE contratos ADD CONSTRAINT fk_contrato_negocio FOREIGN KEY (id_negocio) REFERENCES usuarios(id_usuario) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_deportista') THEN
        ALTER TABLE contratos ADD CONSTRAINT fk_contrato_deportista FOREIGN KEY (id_deportista) REFERENCES usuarios(id_usuario) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_meta_contrato') THEN
        ALTER TABLE metas_contrato ADD CONSTRAINT fk_meta_contrato FOREIGN KEY (id_contrato) REFERENCES contratos(id_contrato) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fondo_contrato') THEN
        ALTER TABLE fondo_garantia ADD CONSTRAINT fk_fondo_contrato FOREIGN KEY (id_contrato) REFERENCES contratos(id_contrato) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_evidencia_meta') THEN
        ALTER TABLE evidencias ADD CONSTRAINT fk_evidencia_meta FOREIGN KEY (id_meta_contrato) REFERENCES metas_contrato(id_meta_contrato) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_archivo_evidencia') THEN
        ALTER TABLE archivos_evidencia ADD CONSTRAINT fk_archivo_evidencia FOREIGN KEY (id_evidencia) REFERENCES evidencias(id_evidencia) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transaccion_meta') THEN
        ALTER TABLE transacciones ADD CONSTRAINT fk_transaccion_meta FOREIGN KEY (id_meta_contrato) REFERENCES metas_contrato(id_meta_contrato) NOT VALID;
    END IF;
END $$;

ALTER TABLE contratos DROP CONSTRAINT IF EXISTS ck_contrato_monto_no_negativo;
ALTER TABLE contratos ADD CONSTRAINT ck_contrato_monto_no_negativo CHECK (monto_total >= 0) NOT VALID;
ALTER TABLE metas_contrato DROP CONSTRAINT IF EXISTS ck_meta_montos_no_negativos;
ALTER TABLE metas_contrato ADD CONSTRAINT ck_meta_montos_no_negativos CHECK (monto_deportista >= 0 AND monto_negocio >= 0) NOT VALID;
ALTER TABLE fondo_garantia DROP CONSTRAINT IF EXISTS ck_fondo_no_negativo;
ALTER TABLE fondo_garantia ADD CONSTRAINT ck_fondo_no_negativo CHECK (monto_congelado >= 0 AND monto_liberado >= 0 AND monto_inicial >= 0) NOT VALID;
